disabled_rules:
 - line_length
 - type_body_length
 - function_body_length
 - file_length

identifier_name:
 excluded:
  - db
  - fd
  - to
  - id
  - x
  - y
  - or
  - eu
  - us

excluded:
 - FMDatabaseAdditionsVariadic.swift
 - FMDatabaseVariadic.swift

nesting:
  type_level:
    warning: 2
  function_level:
    warning: 10

included:
  - Sources
  - Tests
