disabled_rules:
 - line_length
 - type_body_length
 - function_body_length
 - file_length

identifier_name:
 excluded:
  - on
  - eu
  - us

nesting:
  type_level:
    warning: 2
  function_level:
    warning: 10

included:
  - Sources

excluded:
  - Tests

